### ISSUE TITLE
line 40: syntax error near unexpected token `|'

### ISSUE THREAD

**Issue by yasuraok** [ostk0069/github-discussions-notifier#1]
[こちらの記事](https://zenn.dev/ostk0069/articles/a1961b69106dbe)からこのActionにたどり着いてちょっと使わせていただきました。
DiscussionへのCommentの方は期待通りSlackに通知されたのですが、Discussion自体のCreateを試したところ標記のエラーが出ました。

2つのスクリプトをdiffを眺めていたところ、curlにパイプする直前のシングルクオートの位置が違っていました。
https://github.com/ostk0069/github-discussions-notifier/blob/1d90070dde7882dbcb94e2675b2ebb1cda66746e/action.yml#L79-L80

https://github.com/ostk0069/github-discussions-notifier/blob/1d90070dde7882dbcb94e2675b2ebb1cda66746e/action.yml#L127-L128

前者は`|curl`のところでコマンドが途切れている扱いになってる気がしますがいかがでしょうか？もし何らかの別の問題の勘違いでしたらすみません。
ちなみに[パイプまで前行に入れても動作はするようです](https://unix.stackexchange.com/questions/281309/shell-syntax-how-to-correctly-use-to-break-lines)。

---
Zenn側で言及していらっしゃる通り、Discussion自体のCreateは https://slack.github.com/ の方で通知できているので、その意味ではこの件は実害ないのですが、一応見つけたので共有させていただきました。

**Comment by ostk0069** [comment]
こちら言及いただき、ありがとうございます
対応が遅くなってしまい申し訳ありません。対応させていただきます。
