### ISSUE TITLE
Authorization help

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [ostk0069/github-discussions-notifier#2]
Hello!

I've tried to set this up, but I get this error:
![image](https://user-images.githubusercontent.com/35365778/234878237-59cfe7d4-5c7d-4239-b763-be83e68153a3.png)
Can you guide me on what authorizations i need for my Slack bot / app?

**Comment by ostk0069** [comment]
Maybe your slack bot token is invalid.
you can get your token in
OAuth & Permissions > OAuth Tokens for Your Workspace > Bot User OAuth Token

**Comment by PatrikBrynolfsson** [comment]
Thanks! I managed to fix it.
